### PR TITLE
Adding a header/navbar

### PR DESCRIPTION
**Pull request by g0lc0de**
* Added a navbar/ header
* The navbar has 2 items:
  - Logo
  - Github repo link 
* Hovering over the items changes the text size and colour.

 When the screen width is less than 500px, the items stack on top. In summary, the header looks and works great when the width is bigger than 360px(Screen width of most android devices).

### CODE REVIEW

**Comment by pavi2410** [comment]
https://htmlpreview.github.io/?https://github.com/g0lc0de/URL-Inspector/blob/ebe5f006d6ae683053ace9e264589e1e85f940a1/index.html

**Comment by pavi2410** [comment]
Wow! Much better than I expected! Can you please somehow integrate with Github corners which was merged a while ago?

**Comment by g0lc0de** [comment]
Okay, give me some time

**Comment by g0lc0de** [comment]
Done, I added a black Github corner to the navbar.

**Comment by pavi2410** [comment]
Thanks 👍 

Closes #5

**Pull request merged**
