### PR TITLE
Added basic footer section for issue #6

### PR DESCRIPTION
**Pull request by UberschallSamsara**
Wasn't much detail in the issue description, so the text in the footer is just example text.
Happy Hacktoberfest!

### CODE REVIEW

**Comment by pavi2410** [comment]
https://htmlpreview.github.io/?https://github.com/UberschallSamsara/URL-Inspector/blob/AddFooter/index.html

**Comment by UberschallSamsara** [comment]
Hi, I saw your comment but it was just an html preview link - was there more that you wanted to mention?

**Comment by pavi2410** [comment]
I just wanted to preview your wo6

**Pull request closed without merging**
