### PR TITLE
added monospace font

### PR DESCRIPTION
**Pull request by faahim**
+ Added Monospace font
I've used a monospace font stack of system default fonts that are being by GitHub and a lot other big sites these days.

+ Preview
The site will look something like this based on users OS and what fonts are available on their system:

image

### CODE REVIEW

**Comment by pavi2410** [comment]
https://htmlpreview.github.io/?https://github.com/faahim/URL-Inspector/blob/master/index.html

**Comment by pavi2410** [comment]
Looks good to me :)

**Comment by faahim** [comment]
Thanks @pavi2410 ! :smile:

**Comment by pavi2410** [comment]
Congratulations on your first contribution! 🥳🎉

**Comment by faahim** [comment]
Wooo! Amazing!! :heart_eyes: 

Not exactly my first contribution, but the number isn't that big either, haha! Thanks a ton, Pavitra! :slightly_smiling_face:

**Pull request merged**
